# Generated by Django 2.2.24 on 2021-11-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tessio',
            options={'verbose_name': 'tejido', 'verbose_name_plural': 'Tejidos'},
        ),
        migrations.AddField(
            model_name='tessio',
            name='color',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tessio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tessio',
            name='temperature',
            field=models.FloatField(verbose_name='temperatura'),
        ),
    ]
