# Generated by Django 2.2.24 on 2021-11-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211129_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='tessio',
            name='inflamacion',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tessio',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
