# Generated by Django 2.2.24 on 2021-11-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211129_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.RemoveField(
            model_name='tessio',
            name='name',
        ),
        migrations.AlterField(
            model_name='tessio',
            name='inflamacion',
            field=models.FileField(upload_to='', verbose_name='inflamación'),
        ),
    ]
